---
title: "Data Manipulation"
author: "Naama Kipperman"
date: "9/19/2019"
output: github_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```


## Load in FAS data set

``` {r} 

litters_data = read_csv(file="./data/FAS_litters.csv")

# the first thing you want to do when you import a dataset is print it - gives you a sense of what's going on in the dataset

litters_data

# as a next step, we'll often rewrite variable names

litters_data = janitor::clean_names(litters_data)

# read in pups data

pups_data = read_csv(file="./data/FAS_pups.csv")


```


## Selecting things
``` {r}

select (litters_data, group, litter_number)

select(litters_data, litter_number, gd0_weight, starts_with("pups"))

select(litters_data, litter_number, group, gd0_weight)

select(litters_data, litter_number, group, gd0_weight, everything())

select(litters_data, -group)

select(litters_data, litter_number, gd0_weight:pups_survive)

# renaming group in our selected data frame

select(litters_data, GROUP = group)


```


## Filtering 
``` {r} 

filter(litters_data, group == "Mod8")

filter(litters_data, gd_of_birth == 20)

filter(litters_data, group=="Con7" | group=="Con8")

# is equivalent to
filter(litters_data, group %in% c("Con7", "Mod8"))
       
# what about missing values?

filter(litters_data, is.na(gd0_weight)) #don't actually do this
       
# do this

drop_na(litters_data, gd0_weight)

```

# Mutate

``` {r} 
mutate(
  litters_data,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group),
)

# with mutate you're creating new variables 

```

# Arrange
### like proc sort
``` {r} 
arrange(litters_data, pups_born_alive)

arrange(litters_data, desc(pups_born_alive))

arrange(litters_data, pups_born_alive, gd0_weight)
```

## pipe

``` {r}
litters_data = 
  read_csv("./data/FAS_litters.csv") %>%
  janitor::clean_names() %>% 
  select(-pups_survive) %>% 
  mutate(
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)) %>% 
  drop_na(gd0_weight)
    

```
